apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: main-container
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: sidecar-container
      image: busybox
      command: ['sh', '-c', 'while true; do echo sidecar container is running; sleep 10; done']
